/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
  By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
  find the sum of the even-valued terms.*/

import java.io.*;
public class Euler2
{
  public static void main(String []args)
  {
	int n1 = 1, n2 = 2;
	int sum = 0;
	int sum_even = 2;
	while (sum <= 4000000)
	{
		sum = n1+n2;
		n1 = n2;
		n2 = sum;
		if (sum%2==0)
			sum_even += sum;
	}
	System.out.println(sum_even);
  }
}
